jquants_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../data/jquants.duckdb"
      threads: 4
    prod:
      type: duckdb
      path: "../data/jquants.duckdb"
      threads: 4


